[package]
name = "libkoto"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
koto-core = { path = "../koto-core" }
koto-hypr = { path = "../koto-hypr" }
koto-observe = { path = "../koto-observe" }
koto-tmux = { path = "../koto-tmux" }
koto-web = { path = "../koto-web" }
serde_json.workspace = true
