[package]
name = "koto-observe"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
koto-core = { path = "../koto-core" }
memmap2 = "0.9"
png = "0.18"
wayland-backend = "0.3.16"
wayland-client = "0.31.13"
wayland-protocols-wlr = { version = "0.3.12", features = ["client"] }
