[package]
name = "koto"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
base64.workspace = true
clap.workspace = true
koto-core = { path = "../koto-core" }
koto-hypr = { path = "../koto-hypr" }
koto-observe = { path = "../koto-observe" }
koto-policy = { path = "../koto-policy" }
koto-tmux = { path = "../koto-tmux" }
koto-web = { path = "../koto-web" }
regex.workspace = true
libc = "0.2"
serde.workspace = true
serde_json.workspace = true
