[package]
name = "koto-input"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
koto-core = { path = "../koto-core" }
thiserror.workspace = true
wayland-client = "0.31.13"
wayland-backend = "0.3.16"
wayland-protocols-wlr = { version = "0.3.12", features = ["client"] }
wayland-scanner = "0.31.7"
xkbcommon = "0.9"
libc = "0.2"
